DATA:
  SIZE: 320   
  CROP_AREA: 1. ## new_w = CROP_AREA* old_w


STAGE1MODEL:
  BERT_TYPE: "ROBERTA"
  BERT_NAME: "roberta-large"
  IMG_ENCODER: "se_resnext50_32x4d"
  CHECKPOINT: "/home/azureuser/code/AICity_Baseline_2021/stage1/checkpoint_best_eval_p2.pth"

STAGE2MODEL:
  BERT_TYPE: "ROBERTA"
  BERT_NAME: "roberta-large"
  IMG_ENCODER: "efficientnet-b3"
  CHECKPOINT: "/home/azureuser/code/AICity_Baseline_2021/stage2/checkpoint_best_eval.pth"


