DATA:
  USE_MOTION: False
  SIZE: 288
  TRAIN_JSON_PATH: "/mnt/d/meais/Documents/MS/CMU/Courses/11775/Project/AIC22_Track2_NL_Retrieval/train.json"
  EVAL_JSON_PATH: "/mnt/d/meais/Documents/MS/CMU/Courses/11775/Project/AIC22_Track2_NL_Retrieval/val.json"
  CROP_AREA: 1. ## new_w = CROP_AREA* old_w


MODEL:
  NAME: "new"
  BERT_TYPE: "ROBERTA"
  BERT_NAME: "roberta-large"
  IMG_ENCODER: "se_resnext50_32x4d"
  car_idloss: True
  mo_idloss: False
  share_idloss: True
  lang_idloss: True
  CHECKPOINT: "./checkpoints/motion_SE_3CLS_nonlpaug_288.pth"
TRAIN: 
  BATCH_SIZE: 64

TEST:
  QUERY_JSON_PATH: "data/test-queries.json"
  RESTORE_FROM: "checkpoints/motion_SE_3CLS_nonlpaug_288.pth"